grayscale/urls.py
from django.urls import path

from . import views


app_name = 'grayscale'
urlpatterns = [
    path("",views.IndexView.as_view(), name="index"),
    path('inquiry/', views.InquiryView.as_view(), name="inquiry"),
    path('contact-confirm/', views.contact_confirm.as_view(), name="contact_confirm"),
    path('contact-send/', views.contact_send.as_view(), name="contact_send"),
    path('grayscale-list/', views.GrayscaleListView.as_view(), name="grayscale_list"),
    path('grayscale-detail/<int:pk>/', views.GrayscaleDetailView.as_view(), name="grayscale_detail"),
    path('grayscale-create/', views.GrayscaleCreateView.as_view(), name="grayscale_create"),
    path('grayscale-update/<int:pk>/', views.GrayscaleUpdateView.as_view(), name="grayscale_update"),
    path('grayscale-delete/<int:pk>/', views.GrayscaleDeleteView.as_view(), name="grayscale_delete"),
    path('diary_share/',views.ShareListView.as_view(),name='diary_share'),

]

private_grayscale/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from django.urls import path, include
from.import settings_common, settings_dev

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('grayscale.urls')),
    path('accounts/', include('allauth.urls')),
]

# 開発サーバーでメディアを配信できるようにする設定
urlpatterns += static(settings_common.MEDIA_URL, document_root=settings_dev.MEDIA_ROOT)

grayscale/models.py
from accounts.models import CustomUser
from django.db import models

# Create your models here.

class Grayscale(models.Model):
    """日記モデル"""
    user = models.ForeignKey(CustomUser, verbose_name='ユーザー', on_delete=models.PROTECT)
    title = models.CharField(verbose_name='タイトル', max_length=40)
    content = models.TextField(verbose_name='本文', blank=True, null=True)
    photo1 = models.ImageField(verbose_name='写真1', blank=True, null=True)
    photo2 = models.ImageField(verbose_name='写真2', blank=True, null=True)
    photo3 = models.ImageField(verbose_name='写真3', blank=True, null=True)
    checkbox = models.BooleanField(verbose_name='共有', default=False)
    created_at = models.DateTimeField(verbose_name='作成日時', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='更新日時', auto_now=True)

    class Meta:
        verbose_name_plural = 'Grayscale'

    def __str__(self):
        return self.title

grayscale/forms.py
from distutils.command.clean import clean
from distutils.log import error
from multiprocessing import context
import os
from turtle import title
from wsgiref import validate
from django import forms
from django.core.mail import EmailMessage

from.validate import validate_admin
from.models import Grayscale

class InquiryForm(forms.Form):
    name = forms.CharField(label='お名前', max_length=30)
    email = forms.EmailField(label='メールアドレス', validators=[validate_admin])
    title = forms.CharField(label='タイトル', max_length=30)
    def clean_title(self):
        title = self.cleaned_data['title']
        if title in ['hoge', '阿呆', 'fuck']:
            raise forms.ValidationError('この言葉は使えません')
        return title
    message = forms.CharField(label='メッセージ', widget=forms.Textarea)

    def clean(self):
        cleaned_data = super().clean()
        title = cleaned_data.get('title')
        message = cleaned_data.get('message')

        if title == message:
            raise forms.ValidationError('タイトルと同じものは使えません')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['name'].widget.attrs['class'] = 'form-control'
        self.fields['name'].widget.attrs['placeholder'] = 'お名前をここに入力してください。'

        self.fields['email'].widget.attrs['class'] = 'form-control'
        self.fields['email'].widget.attrs['placeholder'] = 'メールアドレスをここに入力してください。'

        self.fields['title'].widget.attrs['class'] = 'form-control'
        self.fields['title'].widget.attrs['placeholder'] = 'タイトルをここに入力してください。'

        self.fields['message'].widget.attrs['class'] = 'form-control'
        self.fields['message'].widget.attrs['placeholder'] = 'メッセージをここに入力してください。'

    def send_email(self):
        name = self.cleaned_data['name']
        email = self.cleaned_data['email']
        title = self.cleaned_data['title']
        message = self.cleaned_data['message']

        subject = 'お問い合わせ {}'.format(title)
        message = '送信者名: {0}\nメールアドレス: {1}\nメッセージ:\n{2}'.format(name, email, message)
        from_email = os.environ.get('FROM_EMAIL')
        to_list = [
            os.environ.get('FROM_EMAIL')
        ]
        cc_list = [
            email
        ]

        message = EmailMessage(subject=subject, body=message, from_email=from_email, to=to_list, cc=cc_list)
        message.send()

class GrayscaleCreateForm(forms.ModelForm):
    class Meta:
        model = Grayscale
        fields = ('title', 'content', 'photo1', 'photo2', 'photo3', "checkbox")
    
    def __init__(self, *args, **kwargs):

        super().__init__(*args, **kwargs)

        cnt=1
        for field in self.fields.values():
            if cnt == 6:
                field.widget.attrs['class'] = 'checkbox'  
            else:  
                field.widget.attrs['class'] = 'form-control'
            cnt += 1

grayscale/views.py
from asyncio.log import logger
from multiprocessing import context
#from typing_extensions import Self
from django.shortcuts import render

# Create your views here.
import logging
from django.urls import reverse_lazy

from django.views import generic
from.forms import InquiryForm

from django.contrib import messages

from django.contrib.auth.mixins import LoginRequiredMixin
from.models import Grayscale

from.forms import InquiryForm,GrayscaleCreateForm

from django.views.generic import ListView
from django.db.models import Q


from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import get_object_or_404


class OnlyYouMixin(UserPassesTestMixin):
    raise_exception = True

    def test_func(self):
        diaryshare = get_object_or_404(Grayscale, pk=self.kwargs['pk'])
        if diaryshare.checkbox == False:
        # URLに埋め込まれた主キーから日記データを1件取得。取得できなかった場合は404エラー
            grayscale = get_object_or_404(Grayscale, pk=self.kwargs['pk'])
        # ログインユーザーと日記の作成ユーザーを比較し、異なればraise_exceptionの設定に従う
            return self.request.user == grayscale.user
        else:
            return True

logger = logging.getLogger(__name__)

class IndexView(generic.TemplateView):
    template_name = "index.html"

class InquiryView(generic.FormView):
    template_name = "inquiry.html"
    form_class = InquiryForm
    success_url = reverse_lazy('grayscale:contact_confirm')

    def get_form(self, form_class=None):
        # contact.hmltで、データを送信した場合
        if 'name' in self.request.POST:
            form_data = self.request.POST
 
        # お問い合わせフォーム確認画面から「戻る」リンクを押した場合や
        # 初回の入力欄表示は以下の表示。
        # セッションにユーザーデータがあれば、それをフォームに束縛
        else:
            form_data = self.request.session.get('form_data', None)
 
        return self.form_class(form_data)

    def form_valid(self, form):
        # 入力した値を、セッションに保存
        self.request.session['form_data'] = self.request.POST
        return super().form_valid(form)



class contact_confirm(generic.TemplateView):
    """お問い合わせフォーム確認ページ"""
 
    template_name = 'contact_confirm.html'
  
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        form_data = self.request.session.get('form_data', None)
        context['form'] = InquiryForm(form_data)
        return context



class contact_send(generic.FormView):
    """お問い合わせ送信"""
 
    template_name = 'inquiry.html'
    form_class = InquiryForm
    success_url = reverse_lazy('grayscale:inquiry')

    def form_valid(self, form):
        form.send_email()
        messages.success(self.request,'メッセージを送信しました。')
        logger.info('Inquiry sent by {}'.format(form.cleaned_data['name']))
        del self.request.session['form_data']
        return super().form_valid(form)
  
class GrayscaleListView(LoginRequiredMixin, generic.ListView):
    context_object_name = 'grayscale_list'
    queryset = Grayscale.objects.order_by('-created_at')
    model = Grayscale
    paginate_by = 2
    template_name = 'grayscale_list.html'

    def get_queryset(self): # 検索機能のために追加
        page = self.request.user
        queryset = Grayscale.objects.filter(user=page.id).order_by('-created_at')
        query = self.request.GET.get('query')

        if query:
            queryset = queryset.filter(
            Q(title__icontains=query)
            )
        return queryset

class GrayscaleDetailView(LoginRequiredMixin, OnlyYouMixin, generic.DetailView):
    model = Grayscale
    template_name = 'grayscale_detail.html'

class GrayscaleCreateView(LoginRequiredMixin, generic.CreateView):
    model = Grayscale
    template_name = 'grayscale_create.html'
    form_class = GrayscaleCreateForm
    success_url = reverse_lazy('grayscale:grayscale_list')

    def form_valid(self, form):
        diary = form.save(commit=False)
        diary.user = self.request.user
        diary.save()
        messages.success(self.request, '日記を作成しました。')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "日記の作成に失敗しました。")
        return super().form_invalid(form)

class GrayscaleUpdateView(LoginRequiredMixin, OnlyYouMixin, generic.UpdateView):
    model = Grayscale
    template_name = 'grayscale_update.html'
    form_class = GrayscaleCreateForm

    def get_success_url(self):
        return reverse_lazy('grayscale:grayscale_detail', kwargs={'pk': self.kwargs['pk']})

    def form_valid(self, form):
        messages.success(self.request, '日記を更新しました。')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "日記の更新に失敗しました。")
        return super().form_invalid(form)

class GrayscaleDeleteView(LoginRequiredMixin, OnlyYouMixin, generic.DeleteView):
    model = Grayscale
    template_name = 'grayscale_delete.html'
    success_url = reverse_lazy('grayscale:grayscale_list')

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, "日記を削除しました。")
        return super().delete(request, *args, **kwargs)

class ShareListView(generic.ListView):
    context_object_name = 'diary_share'
    queryset = Grayscale.objects.filter(checkbox=True).order_by('-created_at')
    model = Grayscale
    paginate_by = 2
    template_name = 'diary_share.html'

    def get_queryset(self): # 検索機能のために追加
        queryset = Grayscale.objects.filter(checkbox=True).order_by('-created_at')
        query = self.request.GET.get('query')

        if query:
            queryset = queryset.filter(
            Q(title__icontains=query)
            )
        return queryset

grayscale/templates/base.html
{% load static %}

<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>{% block title %}{% endblock %}</title>
    <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
    
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v5.15.3/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet" />

    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />

    <!-- My style -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/mystyle.css' %}">
    {% block head %}{% endblock %}
  </head>

  <body>
    <div id="wrapper">
      <!-- Navigation -->
      <nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top">
        <div class="container px-5">
          <a class="navbar-brand" href="{% url 'grayscale:index' %}">Top Page</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
          <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav me-auto">
              <li class="nav-item">
                <a class="nav-link {% block active_inquiry %}{% endblock %}" href="{% url 'grayscale:inquiry' %}">Inquiry</a>
              </li>
              {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link {% block active_grayscale_list %}{% endblock %}" href="{% url 'grayscale:grayscale_list'%}">DIARY LIST</a>
              </li>
              <li class="nav-item">
                <a class="nav-link {% block active_diary_share %}{% endblock %}" href="{% url 'grayscale:diary_share'%}">DIARY SHARE</a>
              </li>
              {% endif %}
            </ul>
            <ul class="navbar-nav ms-auto">
              {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'account_logout' %}">Log Out</a>
              </li>
              {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'account_signup' %}">Sign Up</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'account_login' %}">Log In</a>
              </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>

      {% block header%}{% endblock %}

      {% if messages %}
      <div class="container my-div-style">
          <div class="row">
              <ul class="messages" style="list-style: none;">
                  {% for message in messages %}
                  <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>
                      {{ message }}
                  </li>
                  {% endfor %}
              </ul>          
          </div>
      </div>
    {% endif %}

      {% block contents%}{% endblock %}

      <!-- Footer -->
      <footer class="py-5 bg-black">
        <div class="container px-5"><p class="m-0 text-center text-white small">Copyright &copy; Your Website 2022</p></div>
      </footer>

      <!-- Bootstrap core JS-->
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>
    </div>
  </body>
</html>

grayscale/templates/contact_confirm.html
{% extends 'base.html' %}

{% block title %}お問い合わせ確認 | Inquiry{% endblock %}

{% block contents %}
<div class="quot;container-fluid" style="margin-top: 30px;">
    <div class="kuu" style="margin-top:8em;"></div>
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <div class="card">
        <div class="card-header">お問い合わせ内容確認</div>
        <div class="card-body">
          <div class="card-block">
            <h6 class="card-title">お名前</h6>
            <p class="card-text" style="word-wrap: break-word;">{{ form.name.value }}</p>
            <h6 class="card-title">メールアドレス</h6>
            <p class="card-text" style="word-wrap: break-word;">{{ form.email.value }}</p>
            <h6 class="card-title">タイトル</h6>
            <p class="card-text" style="word-wrap: break-word;">{{ form.title.value }}</p>
            <h6 class="card-title">メッセージ</h6>
            <p class="card-text pb-3" style="word-wrap: break-word;">{{ form.message.value }}</p>
            <form class="my-form" action="{% url 'grayscale:contact_send' %}" method="POST">
                <div class="row">
                    <div class="form-group col-md-11">
                        <div style="display:none">
                            {{ form }}
                            {% csrf_token %}
                        </div>
                        <button type="submit" class="btn btn-primary mt-5 mb-3">送信</button>
                        <a href="{% url 'grayscale:inquiry' %}" class="btn btn-success mt-5 mb-3">戻る</a>
                    </div>
                </div>
            </form>
        </div>
</div><!-- end card-body-->
</div><!-- end card-->
</div>
</div><!-- end row -->
</div><!-- end container-fluid-->
{% endblock %}

grayscale/templates/diary_share.html
{% extends 'base.html' %}
{% load static %}

{% block title %}共有日記一覧 | Share Diary{% endblock %}

{% block active_diary_share_list %}active{% endblock %}

{% block navbar %}<nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top navbar-shrink" id="mainNav">{% endblock %}

{% block head %}
<link href="{% static 'css/clean-blog.css' %}" rel="stylesheet">
{% endblock %}

{% block contents %}
<div class="container px-4 px-lg-5 my-div-style">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
            <div class="d-flex justify-content-end mb-4">
            </div>
            <form method="get">
                <input type="search" value="{{ request.GET.query }}" name="query" type="text" placeholder="タイトルを検索">
                <button>検索</button>
            </form>
            <div class="row">
                <div class="col-sm-4">
                    <a class="btn btn-outline-primary btn-block" href="https://twitter.com/share?url={{ request.scheme }}://{{ request.get_host }}{% url 'grayscale:diary_share' %}&text=記事一覧 - ホームページ名" target="_blank" rel="nofollow">
                        Twitterでシェア
                    </a>
                </div>
                <div class="col-sm-4">
                    <a class="btn btn-outline-primary btn-block" href="https://www.facebook.com/sharer/sharer.php?u={{ request.scheme }}://{{ request.get_host }}{% url 'grayscale:diary_share' %}" target="_blank" rel="nofollow">
                    FaceBookでシェア
                    </a>
                </div>
            </div>

            {% for grayscale in diary_share %}
            <div class="post-preview">
                <a href="{% url 'grayscale:grayscale_detail' grayscale.pk %}">
                    <h2 class="post-title">
                        {{ grayscale.title }}
                    </h2>
                    <h3 class="post-subtitle">
                        {% if grayscale.content != '' %}
                        {{ grayscale.content|truncatechars:20 }}
                        {% else %}
                        {{'※本文が入力されていません'}}
                        {% endif %}
                    </h3>  
                </a>
                <p class="post-meta">{{ grayscale.created_at }}</p>
            </div>
            <hr class="my-4">
            {% empty %}
            <p>日記がありません。</p>
            {% endfor %}

            <!-- ページネーション処理 -->
            {% if is_paginated %}
            <ul class="pagination">
                <!-- 前ページへのリンク -->
                {% if page_obj.has_previous %}
                    <!--検索結果がある場合-->
                    {% if request.GET.query %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}&query={{ request.GET.query }}">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                    {% else %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                    {% endif %}
                {% endif %}

                <!-- ページ数表示 -->
                {% for page_num in page_obj.paginator.page_range %}
                {% if request.GET.query %}
                {% if page_obj.number == page_num %}
                <li class="page-item active"><a class="page-link" href="#">{{ page_num }}</a></li>
                {% else %}
                <li class="page-item"><a class="page-link" href="?page={{ page_num }}&query={{ request.GET.query }}">{{ page_num }}</a></li>
                {% endif %}
                {% else %}
                {% if page_obj.number == page_num %}
                <li class="page-item active"><a class="page-link" href="#">{{ page_num }}</a></li>
                {% else %}
                <li class="page-item"><a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a></li>
                {% endif %}
                {% endif %}
                {% endfor %}

                <!-- 次ページへのリンク -->
                {% if page_obj.has_next %}
                    {% if request.GET.query %} 
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}&query={{ request.GET.query }}">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                    {% else %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                    {% endif %}
                {% endif %}
            </ul>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

grayscale/templates/grayscale_create.html
{% extends 'base.html' %}
{% load static %}

{% block title %}日記作成 | Private Grayscale{% endblock %}

{% block active_grayscale_list %}active{% endblock %}

{% block contents %}
<div class="container my-div-style">
    <h1>日記作成</h1>
    <div class="row">
        <form method="POST" enctype='multipart/form-data'>
            {% csrf_token %}
            <table class="table">
                {{ form.as_table }}
            </table>
            <button class="btn btn-primary" type="submit">作成</button>
            <a href="{% url 'grayscale:grayscale_list'%}"><button type="button" class="btn btn-primary">戻る</button></a>
        </form>
    </div>
</div>
{% endblock %}

grayscale/templates/grayscale_delete.html
{% extends 'base.html' %}
{% load static %}

{% block title %}日記削除 | Private Grayscale{% endblock %}

{% block active_grayscale_list %}active{% endblock %}

{% block contents %}
<div class="container my-div-style">
    <div class="row">
        <form method="POST">
            {% csrf_token %}
            <p>本当に削除しますか？</p>
            <button class="btn btn-primary mt-5" type="submit">削除</button>
            <a class="btn btn-secondary mt-5 ml-2" href="{% url 'grayscale:grayscale_detail' object.pk %}">キャンセル</a>
        </form>
    </div>
</div>
{% endblock %}

grayscale/templates/grayscale_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}日記詳細 | Private Grayscale{% endblock %}

{% block active_grayscale_list %}active{% endblock %}


{% block contents %}
<div class="container my-div-style">
    <div class="row">
        <div class="col-3">
            <strong>タイトル</strong>
        </div>
        <div class="col-9">
            {{ object.title }}
        </div>
    </div>

    <hr>

    <div class="row">
        <div class="col-3">
            <strong>本文</strong>
        </div>
        <div class="col-9">
            {{ object.content|linebreaksbr }}
        </div>
    </div>

    <hr>

    <div class="row">
        <div class="col-3">
            <strong>写真</strong>
        </div>
        <div class="col-3">
            {% if object.photo1 %}
            <img src="{{ object.photo1.url }}" width="200" height="200"/>
            {% endif %}
        </div>
        <div class="col-3">
            {% if object.photo2 %}
            <img src="{{ object.photo2.url }}" width="200" height="200"/>
            {% endif %}
        </div>
        <div class="col-3">
            {% if object.photo3 %}
            <img src="{{ object.photo3.url }}" width="200" height="200"/>
            {% endif %}
        </div>
    </div>

    <hr>

    <div class="row">
        <div class="col-3">
            <strong>作成日時</strong>
        </div>
        <div class="col-9">
            {{ object.created_at }}
        </div>
    </div>

    <hr>

    <div class="row">
        <div class="col-3">
            <strong>更新日時</strong>
        </div>
        <div class="col-9">
            {{ object.updated_at }}
        </div>
    </div>

    {% if object.user == user %}
        <a class="btn btn-success mt-5 mb-3" href="{% url 'grayscale:grayscale_update' object.pk %}">編集</a>
        <a class="btn btn-danger mt-5 ml-2 mb-3" href="{% url 'grayscale:grayscale_delete' object.pk %}">削除</a>
    {% endif %}
    <a class="btn btn-primary mt-5 mb-3" href="{{request.META.HTTP_REFERER}}" type="submit">戻る</a>


</div>
{% endblock %}

grayscale/templates/grayscale_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}日記一覧 | Private Grayscale{% endblock %}

{% block active_grayscale_list %}active{% endblock %}

{% block head %}
<link href="{% static 'css/clean-blog.css' %}" rel="stylesheet">
{% endblock %}

{% block contents %}
<div class="container px-4 px-lg-5 my-div-style">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
            <div class="d-flex justify-content-end mb-4">
                <a class="btn btn-primary float-right" href="{% url 'grayscale:grayscale_create' %}">新規作成</a>
            </div>
            
            <div class="content">
                <form method="get">
                    <input type="search" value="{{ request.GET.query }}" name="query" type="text" placeholder="検索">
                    <button>検索</button>
                </form>
            </div>
            
            {% for grayscale in grayscale_list %}

            <div class="post-preview">
                <a href="{% url 'grayscale:grayscale_detail' grayscale.pk %}">
                    <h2 class="post-title">
                        {{ grayscale.title }}
                    </h2>
                    <h3 class="post-subtitle">
                        {% if grayscale.content != '' %}
                        {{ grayscale.content|truncatechars:20 }}
                        {% else %}
                        {{'※本文が入力されていません'}}
                        {% endif %}
                    </h3>
                </a>
                <p class="post-meta">{{ grayscale.created_at }}</p>
            </div>
            <hr class="my-4">
            {% empty %}
            <p>日記がありません。</p>
            {% endfor %}

            <!-- ページネーション処理 -->
            {% if is_paginated %}
                <ul class="pagination">
                    <!-- 前ページへのリンク -->
                    {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}{% if request.GET.query %}&query={{ request.GET.query }}{% endif %}">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                    {% endif %}

                    <!-- ページ数表示 -->
                    {% for page_num in page_obj.paginator.page_range %}
                    {% if page_obj.number == page_num %}
                    <li class="page-item active"><a class="page-link" href="#">{{ page_num }}</a></li>
                    {% else %}
                    <li class="page-item"><a class="page-link" href="?page={{ page_num }}{% if request.GET.query %}&query={{ request.GET.query }}{% endif %}">{{ page_num }}</a></li>
                    {% endif %}
                    {% endfor %}

                    <!-- 次ページへのリンク -->
                    {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}{% if request.GET.query %}&query={{ request.GET.query }}{% endif %}">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                    {% endif %}
                </ul>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

grayscale/templates/grayscale_update.html
{% extends 'base.html' %}
{% load static %}

{% block title %}日記編集 | Private Grayscale{% endblock %}

{% block active_grayscale_list %}active{% endblock %}

{% block contents %}
<div class="container my-div-style">
    <div class="row">
        <form method="POST" enctype='multipart/form-data'>
            {% csrf_token %}
            <table class="table">
                {{ form.as_table }}
            </table>
            <button class="btn btn-primary" type="submit">更新</button>
            <a class="btn btn-secondary ml-3" href="{% url 'grayscale:grayscale_detail' object.pk %}">キャンセル</a>
        </form>
    </div>
</div>
{% endblock %}

grayscale/templates/inquiry.html
{% extends 'base.html' %}
{% block title %}お問い合わせ | Private Grayscale{% endblock %}

{% block active_inquiry %}active{% endblock %}

{% block contents %}
<div class="container">
    <div class="my-div-style">
        <h1>お問い合わせ</h1>
        <form method="post">
            {% csrf_token %}

            {{ form.non_field_errors }}

            {% for field in form %}
            <div class="mb-4 col-8">
                <label for="{{ field.id_for_label }}" class="form-label">
                    <strong>{{ field.label_tag }}</strong>
                </label>
                {{ field }}
                {{ field.errors }}
            </div>
            {% endfor %}

            <button class="btn btn-primary" type="submit">送信</button>
            <a href="{% url 'grayscale:index'%}">
                <button type="button" class="btn btn-primary">戻る</button>
            </a>
        </form>
    </div>
</div>
{% endblock %}